# Generated by Django 6.0 on 2025-12-26 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='အမျိုးအစားအမည်')),
                ('description', models.TextField(blank=True, null=True, verbose_name='အကြောင်းအရာ')),
            ],
            options={
                'verbose_name': 'ကုန်ပစ္စည်းအမျိုးအစား',
                'verbose_name_plural': 'ကုန်ပစ္စည်းအမျိုးအစားများ',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('branch_group', models.CharField(blank=True, help_text='ဆိုင်ခွဲအမည်', max_length=100, null=True)),
                ('location_type', models.CharField(choices=[('branch', 'Retail Branch'), ('warehouse', 'Central Warehouse')], default='branch', max_length=10)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_sale_location', models.BooleanField(default=False, help_text='ဝန်ထမ်းများ ရောင်းချရန်အတွက် အသုံးပြုသည့် နေရာဟုတ်/မဟုတ်။')),
                ('staff_assigned', models.ManyToManyField(blank=True, help_text='ဤ Location (ဆိုင်/ဂိုဒေါင်) တွင် တာဝန်ပေးထားသော ဝန်ထမ်းများ။', related_name='assigned_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU/Product ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='ပစ္စည်းပုံ')),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='လက်လီဈေး')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='မူရင်းကုန်ကျစရိတ်')),
                ('is_serial_tracked', models.BooleanField(default=False, verbose_name='Serial No. ဖြင့် ခြေရာခံမည်')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category', verbose_name='အမျိုးအစား')),
            ],
            options={
                'verbose_name': 'ပစ္စည်းစာရင်း (Inventory)',
                'verbose_name_plural': 'ပစ္စည်းစာရင်းများ (Inventory)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaleTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending (အတည်ပြုရန်စောင့်ဆိုင်းဆဲ)'), ('approved', 'Approved (အတည်ပြုပြီး)'), ('rejected', 'Rejected (ငြင်းပယ်ပြီး)')], default='pending', max_length=10)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer')),
                ('sale_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.location')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('sale_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='inventory.saletransaction')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('notification_type', models.CharField(default='system', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sale_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.saletransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('movement_type', models.CharField(choices=[('inbound', 'Inbound (Stock Received/Return)'), ('outbound', 'Outbound (Sale/Withdrawal)'), ('transfer', 'Transfer (Location Change)'), ('adjustment', 'Adjustment (Count/Fix)'), ('rejected', 'Rejected Sale Log')], default='adjustment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('moved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moved_from', to='inventory.location')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moved_to', to='inventory.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('sale_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='inventory.saletransaction')),
            ],
        ),
        migrations.CreateModel(
            name='SerialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Serial No.')),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('sold', 'Sold'), ('defective', 'Defective'), ('pending_sale', 'Pending Sale Approval')], default='in_stock', max_length=20)),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serial_items_in_stock', to='inventory.location', verbose_name='လက်ရှိတည်နေရာ')),
                ('product', models.ForeignKey(limit_choices_to={'is_serial_tracked': True}, on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('sale_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial_item', to='inventory.saletransaction')),
            ],
            options={
                'verbose_name': 'Serial Number Item',
                'verbose_name_plural': 'Serial Number Items',
                'ordering': ['serial_number'],
            },
        ),
    ]
