# Generated by Django 5.2.9 on 2026-02-14 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_sale_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty_months',
            field=models.PositiveIntegerField(default=0, verbose_name='Warranty (လ)'),
        ),
        migrations.CreateModel(
            name='WarrantyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warranty_start_date', models.DateField(verbose_name='Warranty စသည့်ရက်')),
                ('warranty_end_date', models.DateField(verbose_name='Warranty ကုန်မည့်ရက်')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('sale_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.saletransaction')),
                ('serial_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_record', to='inventory.serialitem')),
            ],
            options={
                'verbose_name': 'Warranty မှတ်တမ်း',
                'verbose_name_plural': 'Warranty မှတ်တမ်းများ',
            },
        ),
    ]
