# Generated by Django 5.2.9 on 2026-02-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_add_warranty_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('warehouse', 'ဂိုဒေါင် (Central Warehouse)'), ('branch', 'ဆိုင်ခွဲ (Retail Branch)'), ('shop_floor', 'ရောင်းချရန်နေရာ (Shop Floor)')], default='branch', max_length=10),
        ),
    ]
