# Generated by Django 5.2.9 on 2026-02-15 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_phase_abc_location_staff_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Bundle အမည်')),
                ('description', models.TextField(blank=True, null=True, verbose_name='အကြောင်းအရာ')),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Bundle SKU/Code')),
                ('bundle_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Bundle ဈေး (သတ်မှတ်ထားပါက ဤဈေးသုံးမည်)')),
                ('is_active', models.BooleanField(default=True, verbose_name='အသက်သွင်းထား')),
            ],
            options={
                'verbose_name': 'ပစ္စည်းအစု (Bundle)',
                'verbose_name_plural': 'ပစ္စည်းအစုများ (Bundles)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='အရေအတွက်')),
                ('is_optional', models.BooleanField(default=False, verbose_name='ရွေးချယ်မှု (True ဖြစ်လျှင် ဝယ်ယူသူက ဖယ်နိုင်သည်)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='အစဉ်လိုက်')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.bundle')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Bundle ပစ္စည်းတစ်ခု',
                'verbose_name_plural': 'Bundle ပစ္စည်းများ',
                'ordering': ['bundle', 'sort_order', 'id'],
                'unique_together': {('bundle', 'product')},
            },
        ),
    ]
