# Generated by Django 5.2.9 on 2026-02-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_add_bundle_bundleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_no',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Model No. (ရှာမယ်ဆိုရင် index သုံးမယ်)'),
        ),
        migrations.AddField(
            model_name='product',
            name='serial_number_required',
            field=models.BooleanField(default=False, verbose_name='Serial number required (Inverter/Battery စသည့် တစ်ခုချင်း ခြေရာခံရမည်)'),
        ),
    ]
