# Generated by Django 5.2.9 on 2026-02-15 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_sku_blank_auto_generate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ဆိုင်/ဆိုင်ခွဲအမည်')),
                ('address', models.TextField(blank=True, null=True, verbose_name='လိပ်စာ')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ကုဒ်')),
            ],
            options={
                'verbose_name': 'ဆိုင်/ဆိုင်ခွဲ (Site)',
                'verbose_name_plural': 'ဆိုင်များ/ဆိုင်ခွဲများ (Sites)',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='location',
            name='branch_group',
            field=models.CharField(blank=True, help_text='ဆိုင်ခွဲအမည် (ဟောင်း)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('warehouse', 'ဂိုဒေါင် (Warehouse)'), ('branch', 'ဆိုင်ခွဲ (Branch)'), ('shop_floor', 'ရောင်းချရန်နေရာ (Shop Floor)')], default='branch', max_length=10),
        ),
        migrations.AddField(
            model_name='location',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.site', verbose_name='ဆ/ဆိုင်ခွဲ (Site)'),
        ),
    ]
