# Generated by Django 5.2.9 on 2026-02-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'ကုန်ပစ္စည်းအမျိုးအစား', 'verbose_name_plural': 'ကုန်ပစ္စည်းအမျိုးအစားများ'},
        ),
        migrations.AlterModelOptions(
            name='exchangeratelog',
            options={'ordering': ['-date', 'currency'], 'verbose_name': 'Exchange Rate Log', 'verbose_name_plural': 'Exchange Rate Logs'},
        ),
        migrations.AlterField(
            model_name='exchangeratelog',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='exchangeratelog',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Rate (MMK per unit)'),
        ),
    ]
