# Generated by Django 5.2.9 on 2026-03-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_seed_card_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='အမည်')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'ရာခိုင်နှုန်း (%)'), ('FIXED_AMOUNT', 'သတ်မှတ်ပမာဏ (MMK)')], default='PERCENTAGE', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=0, help_text='Percentage (0-100) or fixed MMK amount', max_digits=12)),
                ('min_purchase', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='အနည်းဆုံး ဝယ်ယူငွေ (MMK)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='စတင်ရက်')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='ပြီးဆုံးရက်')),
                ('is_active', models.BooleanField(default=True, verbose_name='အသက်သွင်းထား')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'လျှော့ဈေး စည်းမျဉ်း',
                'verbose_name_plural': 'လျှော့ဈေး စည်းမျဉ်းများ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('PCS', 'Pieces'), ('CARD', 'Card'), ('SET', 'Sets'), ('MTR', 'Meters'), ('ROL', 'Rolls'), ('KG', 'Kilograms'), ('BOX', 'Boxes'), ('PKG', 'Packages'), ('UNT', 'Units')], default='PCS', max_length=10, verbose_name='Unit Type'),
        ),
    ]
