# Generated by Django 5.2.9 on 2026-03-04 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_add_discount_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='အမည်')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='ဖော်ပြချက်')),
                ('is_required', models.BooleanField(default=False, verbose_name='ရွေးရမည်')),
                ('max_selections', models.PositiveSmallIntegerField(default=1, verbose_name='အများဆုံး ရွေးချယ်မှု')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modifier အုပ်စု',
                'verbose_name_plural': 'Modifier အုပ်စုများ',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModifierOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='အမည်')),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ဈေး ထပ်ထည့်ငွေ (MMK)')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='inventory.modifiergroup')),
            ],
            options={
                'verbose_name': 'Modifier ရွေးချယ်စရာ',
                'verbose_name_plural': 'Modifier ရွေးချယ်စရာများ',
                'ordering': ['group', 'display_order', 'name'],
            },
        ),
    ]
