# Generated by Django 6.0 on 2025-12-27 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepairService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('item_name', models.CharField(max_length=200)),
                ('problem_description', models.TextField()),
                ('total_estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_deposit_paid', models.BooleanField(default=False)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateField()),
                ('status', models.CharField(choices=[('received', 'လက်ခံရရှိ (Pending)'), ('fixing', 'ပြင်ဆင်ဆဲ (In Progress)'), ('ready', 'လာယူနိုင်ပြီ (Ready for Pickup)'), ('completed', 'ပေးအပ်ပြီး'), ('cancelled', 'ပယ်ဖျက်')], default='received', max_length=20)),
                ('is_customer_notified', models.BooleanField(default=False, help_text='ဖုန်းဆက်ပြီး/မပြီး')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='customer.customer')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
