# Generated by Django 5.2.9 on 2026-02-14 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_add_warranty_system'),
        ('service', '0004_repairservice_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='repairservice',
            name='labour_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='လုပ်အားခ'),
        ),
        migrations.AlterField(
            model_name='repairservice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='RepairSparePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=200, verbose_name='အမည်')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('product', models.ForeignKey(blank=True, help_text='Inventory မှ ပစ္စည်း (ရွေးချယ်နိုင်သည်)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
                ('repair_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts', to='service.repairservice')),
            ],
        ),
        migrations.CreateModel(
            name='RepairStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repair_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='service.repairservice')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
