# Generated by Django 5.2.9 on 2026-02-17 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0004_alter_customer_id'),
        ('inventory', '0011_add_payment_method_and_payment_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_no', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Installation No.')),
                ('installation_address', models.TextField(verbose_name='တပ်ဆင်မည့်လိပ်စာ')),
                ('installation_date', models.DateField(verbose_name='တပ်ဆင်မည့်ရက်စွဲ')),
                ('estimated_completion_date', models.DateField(blank=True, null=True, verbose_name='ခန့်မှန်းပြီးစီးမည့်ရက်')),
                ('status', models.CharField(choices=[('pending', 'Pending (စောင့်ဆိုင်းဆဲ)'), ('in_progress', 'In Progress (တပ်ဆင်ဆဲ)'), ('completed', 'Completed (ပြီးစီးပြီး)'), ('signed_off', 'Signed Off (လက်မှတ်ရေးထိုးပြီး)'), ('cancelled', 'Cancelled (ပယ်ဖျက်)')], default='pending', max_length=20, verbose_name='အခြေအနေ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='ဖော်ပြချက်')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='မှတ်ချက်')),
                ('customer_signature', models.ImageField(blank=True, null=True, upload_to='installation_signatures/', verbose_name='ဖောက်သည် လက်မှတ်')),
                ('signed_off_at', models.DateTimeField(blank=True, null=True, verbose_name='လက်မှတ်ရေးထိုးသည့်ရက်စွဲ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='ပြီးစီးသည့်ရက်စွဲ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_installations', to=settings.AUTH_USER_MODEL, verbose_name='ဖန်တီးသူ')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations', to='customer.customer', verbose_name='ဖောက်သည်')),
                ('sale_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_jobs', to='inventory.saletransaction', verbose_name='ရောင်းချမှု')),
                ('signed_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_off_installations', to=settings.AUTH_USER_MODEL, verbose_name='လက်မှတ်ရေးထိုးသူ')),
                ('technician', models.ForeignKey(blank=True, limit_choices_to={'role_obj__name__icontains': 'technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_installations', to=settings.AUTH_USER_MODEL, verbose_name='တပ်ဆင်သူ (Technician)')),
            ],
            options={
                'verbose_name': 'တပ်ဆင်မှု (Installation Job)',
                'verbose_name_plural': 'တပ်ဆင်မှုများ (Installation Jobs)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstallationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installation_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='installation.installationjob')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Status မှတ်တမ်း',
                'verbose_name_plural': 'Status မှတ်တမ်းများ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='installationjob',
            index=models.Index(fields=['status', '-created_at'], name='installatio_status_de865c_idx'),
        ),
        migrations.AddIndex(
            model_name='installationjob',
            index=models.Index(fields=['technician', 'status'], name='installatio_technic_e08647_idx'),
        ),
    ]
