# Generated by Django 5.2.9 on 2026-02-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='accounting__transac_01ce29_idx',
            old_name='accounting__transac_7a8b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='accounting__transac_0accd6_idx',
            old_name='accounting__transac_8d9e0f_idx',
        ),
    ]
