# Generated by Django 5.2.9 on 2026-02-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('first_run_at', models.DateTimeField(auto_now_add=True)),
                ('deployment_mode', models.CharField(choices=[('on_premise', 'On-Premise (စက်ထဲမှာထား)'), ('hosted', 'Hosted (Server ပေါ်တင်)')], default='on_premise', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Installation',
                'verbose_name_plural': 'App Installations',
                'db_table': 'license_app_installation',
            },
        ),
        migrations.CreateModel(
            name='AppLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(choices=[('trial', 'Trial (၁ လ + ၅ ရက် grace)'), ('on_premise_perpetual', 'On-Premise (တစ်ခါဝယ် အမြဲသုံး)'), ('hosted_annual', 'Hosted (တစ်နှစ်တစ်ခါ renewal)')], max_length=30)),
                ('machine_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('license_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App License',
                'verbose_name_plural': 'App Licenses',
                'db_table': 'license_app_license',
            },
        ),
    ]
