# Generated by Django 5.2.9 on 2026-02-14 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0004_phase_abc_location_staff_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assignment_type',
            field=models.CharField(choices=[('fixed', 'ပုံသေ (တစ်ဆိုင်တည်း)'), ('rotating', 'အလှည့်ကျ (ဆိုင်များကို လဲလှည့်သွားသည်)')], default='fixed', help_text='ပုံသေ = တစ်ဆိုင်တည်း၊ အလှည့်ကျ = ဆိုင်များကို လဲလှည့်သွားသည်', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_location',
            field=models.ForeignKey(blank=True, help_text='ပုံသေထားသော ဝန်ထမ်းအတွက် မိမိဆိုင်', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_staff', to='inventory.location'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='StaffSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_sessions', to='inventory.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'get_latest_by': 'started_at',
            },
        ),
    ]
