# Generated by Django 5.2.9 on 2026-02-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_user_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='idx_user_role',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='idx_user_location',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='idx_user_active_staff',
        ),
    ]
