# Generated by Django 5.2.9

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_shopsettings_trial_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Outlet Name')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone')),
                ('is_main_branch', models.BooleanField(default=False, verbose_name='Main Branch')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Outlet',
                'verbose_name_plural': 'Outlets',
                'ordering': ['-is_main_branch', 'name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='primary_outlet',
            field=models.ForeignKey(
                blank=True,
                help_text='Branch lock: staff see only this outlet. Owner: null = all outlets.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='staff',
                to='core.outlet',
            ),
        ),
    ]
