"""
Django settings for WeldingProject project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env for production (Google Sheets, Telegram, etc.)
env = environ.Env(
    TELEGRAM_BOT_TOKEN=(str, ''),
    TELEGRAM_CHAT_ID=(str, ''),
    GOOGLE_SHEETS_SPREADSHEET_ID=(str, ''),
    GOOGLE_SHEETS_SHEET_NAME=(str, 'Registrations'),
    GOOGLE_SHEETS_CREDENTIALS_JSON=(str, ''),
    GOOGLE_SHEETS_JSON=(str, ''),
)
_env_file = BASE_DIR / '.env'
if _env_file.exists():
    env.read_env(str(_env_file))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-9_p1uorl3hht-aeu@f4-oy)i44nb-+9z2yce@v_n=r$321#-*^')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('true', '1', 'yes')

# ALLOWED_HOSTS: from env; if DEBUG=True use ['*'] for dev/deploy flexibility
_raw = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')
_allowed = [h.strip() for h in _raw.split(',') if h.strip()]
ALLOWED_HOSTS = ['*'] if DEBUG else (_allowed or ['localhost', '127.0.0.1'])

# External integrations (from .env in production)
TELEGRAM_BOT_TOKEN = env('TELEGRAM_BOT_TOKEN')
TELEGRAM_CHAT_ID = env('TELEGRAM_CHAT_ID')
GOOGLE_SHEETS_SPREADSHEET_ID = env('GOOGLE_SHEETS_SPREADSHEET_ID')
GOOGLE_SHEETS_SHEET_NAME = env('GOOGLE_SHEETS_SHEET_NAME')
# GOOGLE_SHEETS_JSON is the .env var name; Django uses GOOGLE_SHEETS_CREDENTIALS_JSON (path to service account JSON)
GOOGLE_SHEETS_CREDENTIALS_JSON = env('GOOGLE_SHEETS_CREDENTIALS_JSON') or env('GOOGLE_SHEETS_JSON')

# Demo / low-resource: single backend for all shops; subdomain → outlet; restrict admin for demo owners
DEMO_MODE = os.environ.get('DEMO_MODE', 'False').lower() in ('true', '1', 'yes')

# Fix AutoField warnings
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Application definition

INSTALLED_APPS = [
    'daphne',  # ✅ daphne ကို 'django.contrib.staticfiles' ရဲ့ အပေါ်ဆုံးမှာ ထည့်ပါ
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party Apps
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'django_filters',
    

    # Project Apps
    'core.apps.CoreConfig',
    'license.apps.LicenseConfig',
    'inventory.apps.InventoryConfig',
    'customer.apps.CustomerConfig',
    'notification.apps.NotificationConfig',
    'service.apps.ServiceConfig',
    'ai.apps.AiConfig',
    'accounting.apps.AccountingConfig',
    'installation.apps.InstallationConfig',

    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static (DRF browsable API CSS, admin) in Docker/production
    'core.security_middleware.SecurityHeadersMiddleware',  # SRE: Security headers
    'license.middleware.LicenseCheckMiddleware',
    'core.trial_middleware.TrialExpiryMiddleware',
    'core.sre_middleware.StructuredLoggingMiddleware',  # SRE: Structured logging (user_id, status_code)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'core.outlet_middleware.SubdomainOutletMiddleware',  # Subdomain → outlet_id (demo multi-tenant)
    'core.outlet_middleware.DemoAdminRestrictMiddleware',  # DEMO_MODE: block /admin/ for demo owners
]

ROOT_URLCONF = 'WeldingProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'WeldingProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
_db_url = os.environ.get('DATABASE_URL')
if _db_url:
    import dj_database_url
    _db_config = dj_database_url.parse(_db_url)
    # Host override: when running from host (not in Docker), set DATABASE_HOST=localhost
    # so "postgres" in DATABASE_URL is replaced and DB is reachable.
    _db_host_override = os.environ.get('DATABASE_HOST')
    if _db_host_override:
        _db_config['HOST'] = _db_host_override
    # ဆိုင်ခွဲများ တစ်ပြိုင်တည်းသုံးစွဲမှု - connection reuse (60s)
    _db_config.setdefault('CONN_MAX_AGE', 60)
    DATABASES = {'default': _db_config}
else:
    # EXE: use HOBOPOS_DB_DIR for persistent db (next to HoBoPOS.exe)
    _db_dir = os.environ.get('HOBOPOS_DB_DIR')
    if _db_dir:
        _db_path = Path(_db_dir) / 'db.sqlite3'
        _db_path.parent.mkdir(parents=True, exist_ok=True)
    else:
        _db_path = BASE_DIR / 'db.sqlite3'
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': str(_db_path),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Yangon'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Vite frontend build (Docker copies dist → /app/static_frontend)
STATIC_FRONTEND_DIR = BASE_DIR / 'static_frontend'
STATICFILES_DIRS = []
if STATIC_FRONTEND_DIR.exists():
    STATICFILES_DIRS.append(('', STATIC_FRONTEND_DIR))

MEDIA_URL = '/media/'
# EXE: media next to db (persistent)
_data_dir = os.environ.get('HOBOPOS_DB_DIR')
MEDIA_ROOT = Path(_data_dir) / 'media' if _data_dir else BASE_DIR / 'media'
# When Host is "localhost" without port, build_absolute_uri yields http://localhost/... → browser hits port 80 → ERR_CONNECTION_REFUSED. Set this so media URLs use the correct origin (e.g. http://localhost:8000).
MEDIA_BASE_URL = os.environ.get('MEDIA_BASE_URL', 'http://localhost:8000' if DEBUG else '')


# CORS Configuration - Frontend (Vite 5173 / Docker 80) must talk to Backend (8000)
_CORS_EXTRA = os.environ.get('CORS_EXTRA_ORIGINS', '')
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost",
    "http://localhost:80",
    "http://127.0.0.1",
    "http://127.0.0.1:80",
    "https://pos.hobocustomsoftware.com",
    "http://pos.hobocustomsoftware.com",
] + [o.strip() for o in _CORS_EXTRA.split(',') if o.strip()]
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL', 'True').lower() in ('true', '1', 'yes')

# CSRF_TRUSTED_ORIGINS (Django 4+) - set in production
_CSRF_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _CSRF_ORIGINS.split(',') if o.strip()]

# settings.py
CORS_ALLOW_HEADERS = [
    "accept",
    "authorization", 
    "content-type",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]


AUTH_USER_MODEL = 'core.User'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Pagination: standard across list endpoints (?page=, ?page_size=)
    'DEFAULT_PAGINATION_CLASS': 'core.pagination.StandardPageNumberPagination',
    'PAGE_SIZE': 20,
    # API rate limiting - ဆိုင်ခွဲ/အသုံးပြုသူများ တစ်ပြိုင်တည်းသုံးစွဲမှု အတွက်
    'DEFAULT_THROTTLE_CLASSES': (
        'core.throttling.ApiUserThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'license_activate': '10/min',
        'remote_license': '30/min',
        'auth': '20/min',
        'api_user': '200/min',
    },
}

# Optional: JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60), # Access Token သက်တမ်း (၁ နာရီ)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7), # Refresh Token သက်တမ်း (၇ ရက်)
}


LOGIN_REDIRECT_URL = '/'

LOGIN_URL = 'api/token/'

LOGOUT_REDIRECT_URL = '/'



# SPECTACULAR SETTINGS (Optional)
SPECTACULAR_SETTINGS = {
    'TITLE': 'Welding Inventory Management API',
    'DESCRIPTION': 'API Documentation for Staff Sales and Admin Approval Flow.',
    'VERSION': '1.0.0',
    # JWT Authorization Header ကို Swagger ထဲမှာ ထည့်သွင်းခွင့်ပေးရန်
    'COMPONENT_SPLIT_REQUEST': True,
    'SECURITY': [
        {
            'BearerAuth': [],
        },
    ],
    'SWAGGER_UI_SETTINGS': {
        'filter': True, # API များကို စစ်ထုတ်နိုင်ရန်
        'deepLinking': True,
    },
    
    # Permission များကို စစ်ဆေးရန် (JWT Token မပါရင် ဝင်လို့မရအောင်)
    'SERVE_INCLUDE_SCHEMA': False, # Schema ကို တိုက်ရိုက်ခေါ်ခြင်းကို ပိတ်ထားသည်
    'SERVE_PUBLIC': False, # Public Access ကို ပိတ်ထားသည်
}

# ============================================================================
# Celery Configuration (for background tasks like exchange rate fetching)
# ============================================================================
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Yangon'
CELERY_ENABLE_UTC = True

# Import Celery Beat schedule
try:
    from .celerybeat_schedule import CELERY_BEAT_SCHEDULE
    CELERY_BEAT_SCHEDULE = CELERY_BEAT_SCHEDULE
except ImportError:
    CELERY_BEAT_SCHEDULE = {}


ASGI_APPLICATION = 'WeldingProject.asgi.application'


# Cache (for rate limiting, etc.) - Redis when REDIS_URL set; else local (run_lite / EXE no Redis)
_redis_url = os.environ.get('REDIS_URL', '').strip()
if _redis_url:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _redis_url,
        },
    }
else:
    CACHES = {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}

# 2. CHANNEL LAYERS Configuration (Redis)
if _redis_url:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [_redis_url]},
        },
    }
else:
    # EXE/Standalone: In-memory (no Redis)
    CHANNEL_LAYERS = {"default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}}


# --- Security (Production) ---
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'false').lower() in ('true', '1', 'yes')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# --- Logging (SRE Standard: Structured Logging) ---
import logging

class SafeFormatter(logging.Formatter):
    """Formatter that safely handles missing fields (for Django internal logging)"""
    def format(self, record):
        # Add default values for missing fields
        if not hasattr(record, 'user_id'):
            record.user_id = None
        if not hasattr(record, 'status_code'):
            record.status_code = '-'
        if not hasattr(record, 'method'):
            record.method = '-'
        if not hasattr(record, 'path'):
            record.path = getattr(record, 'pathname', '-')
        if not hasattr(record, 'response_time_ms'):
            record.response_time_ms = '-'
        if not hasattr(record, 'ip'):
            record.ip = '-'
        return super().format(record)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'structured': {
            '()': SafeFormatter,
            'format': '{levelname} {asctime} user_id={user_id} status_code={status_code} method={method} path={path} response_time_ms={response_time_ms} ip={ip}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        # Django request logger - use simple formatter to avoid KeyError
        'django.request': {
            'level': 'INFO',
            'handlers': ['console'],
            'propagate': False,  # Don't propagate to root
        },
        # Django server logger (for runserver) - also use simple formatter
        'django.server': {
            'level': 'INFO',
            'handlers': ['console'],
            'propagate': False,
        },
        # Django utils logger (includes log_response)
        'django.utils': {
            'level': 'INFO',
            'handlers': ['console'],
            'propagate': False,
        },
        'django.security': {
            'level': 'WARNING',
            'handlers': ['console'],
            'propagate': False,
        },
    },
}