# Generated by Django 5.2.9 on 2026-02-14 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_add_customer_email'),
        ('inventory', '0004_phase_abc_location_staff_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='preferred_branch',
            field=models.ForeignKey(blank=True, help_text='ကြိုက်နှစ်သက်သော ဆိုင်ခွဲ (Repair လာယူမည့်နေရာ သို့မဟုတ် ဝယ်ယူမှုအတွက်)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_customers', to='inventory.location'),
        ),
    ]
