# Generated by Django 6.0 on 2026-02-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_phase_abc_location_staff_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
